### ISSUE TITLE
Decide features

### ISSUE THREAD

**Issue by coditva** [BitsAiims2017/web#1]
Add some suggestions for the features in an inventory management system here.

**Comment by coditva** [comment]
Basic/Compulsory:
- Add
- Delete
- Edit
- Search
- Find expired
- Sort inventory items according to date / price / etc.

**Comment by a-y-u-s-h** [comment]
UI Features: 

- Minimum Scrolling.
- Pagination wherever needed.
- RSCSS, Object Oriented CSS, SMACSS or a combination of these.
- Responsiveness => Customized Bootstrap or Semantic UI. 
- Data Visualization, if possible.
- A dark and light theme option button ?
- Do we need SFX for UI hover and click? Might be a bit of an overkill. (DONT YOU DARE!)
- Keyboard controlled UI. Bindkeys to jump to some important components, like cmd + S for Search or something.

To do: 

- Figure out a way to make [this data](https://files.gitter.im/BITS-Developers/Lobby/Lw5w/Essential-Medicine-List-AIIMS-Bhopal.pdf) look good on web, make it so that it is easy to use at multiple places such as in data viz and on usual pages.

**Comment by coditva** [comment]
I like the data visualization thing. this should be done!

**Comment by a-y-u-s-h** [comment]
Will be done then, but data visualization may not be responsive..>_> I'll have to think how to tackle that, pretty sure it'll be a problem.

**Comment by a-y-u-s-h** [comment]
Other Functionality Features: 

- From this [wikipedia article](https://en.wikipedia.org/wiki/Inventory_management_software) 
- PDF Report generation ?

**Comment by a-y-u-s-h** [comment]
More ideas needed for : 

- ML/AI integration, either by an API or a custom made training model. (How can we use it?)
- Some use cases of ML/AI in our project. (Where can we use it?)
- Development automation. (Some really cool task automation thingies you could find.)

**Comment by coditva** [comment]
Automation:
- [x] Linting/Maintaining code quality
- [x] Build (eg automatically generate CSS in front-end etc) (use gulp or grunt, maybe?) (..Webpack)
- [ ] Deploying
- [x] Testing (implemented in api)
- [x] Documentation (implemented in api)

**Comment by a-y-u-s-h** [comment]
ML Implementation : 

-  [ML in Javascript : Full Text Search](http://burakkanber.com/blog/machine-learning-full-text-search-in-javascript-relevance-scoring/)

**Comment by coditva** [comment]
Add option for backup and restore
